// src/styles/theme.js

import { useTheme } from "../components/ThemeProvider";

// Couleurs de base
export const theme = {
  bg: "#f5f7fb",
  card: "#ffffff",
  accent: "#4f46e5",
  accentLight: "#6366f1",
  danger: "#ef4444",
  warning: "#f59e0b",
  success: "#10b981",
  text: "#1e293b",
  grave: "#ef4444",
  moyenne: "#f59e0b",
  legere: "#10b981",
  radius: "16px",
  radiusSm: "12px",
  fontSans: "'Inter', system-ui, sans-serif",
  fontHeading: "'Inter', system-ui, sans-serif",
  fontMono: "'Inter', ui-monospace, monospace",
};

export const graviteColor = (g) =>
  g === "Grave" ? theme.grave : g === "Moyenne" ? theme.warning : theme.success;

export const getStyles = (dark) => {
  const colors = {
    bg: dark ? "#0f172a" : "#f5f7fb",
    card: dark ? "#1e293b" : "#ffffff",
    text: dark ? "#e2e8f0" : "#1e293b",
    textMuted: dark ? "#94a3b8" : "#64748b",
    textDim: dark ? "#94a3b8" : "#94a3b8",
    border: dark ? "rgba(255,255,255,0.1)" : "rgba(0,0,0,0.05)",
    inputBg: dark ? "#0f172a" : "#f9fafb",
    accent: dark ? "#818cf8" : "#4f46e5",
    shadow: dark ? "0 4px 6px -1px rgba(0,0,0,0.3)" : "0 4px 6px -1px rgba(0,0,0,0.05)",
  };

  return {
    // ---- Global ----
    wrapper: {
      minHeight: "100vh",
      backgroundColor: colors.bg,
      fontFamily: theme.fontSans,
      color: colors.text,
      display: "flex",
      flexDirection: "column",
      transition: "background-color 0.3s, color 0.3s",
    },
    navbar: {
      background: colors.card,
      borderBottom: `1px solid ${colors.border}`,
      boxShadow: "0 1px 3px rgba(0,0,0,0.03)",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "0 20px",
      height: 64,
      position: "sticky",
      top: 0,
      zIndex: 100,
      flexWrap: "wrap",
      transition: "background-color 0.3s",
    },
    navbarBrand: {
      fontWeight: 800,
      fontSize: 20,
      background: "linear-gradient(135deg, #4f46e5, #7c3aed)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      marginRight: 20,
      fontFamily: theme.fontHeading,
    },
    navTabs: {
      display: "flex",
      gap: 8,
      flex: 1,
      justifyContent: "center",
      overflowX: "auto",
    },
    tab: (active) => ({
      padding: "8px 16px",
      borderRadius: 20,
      fontWeight: 600,
      fontSize: 14,
      cursor: "pointer",
      color: active ? "#fff" : colors.textMuted,
      background: active ? colors.accent : "transparent",
      border: "none",
      transition: "all 0.2s",
      whiteSpace: "nowrap",
      fontFamily: theme.fontSans,
    }),
    bottomNav: {
      position: "fixed",
      bottom: 0,
      left: 0,
      right: 0,
      background: colors.card,
      borderTop: `1px solid ${colors.border}`,
      display: "flex",
      justifyContent: "space-around",
      padding: "8px 0",
      zIndex: 100,
      transition: "background-color 0.3s",
    },
    bottomTab: (active) => ({
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: 2,
      color: active ? colors.accent : colors.textMuted,
      fontWeight: active ? 700 : 500,
      fontSize: 11,
      background: "none",
      border: "none",
      cursor: "pointer",
      flex: 1,
      fontFamily: theme.fontSans,
    }),
    main: {
      flex: 1,
      width: "100%",
      maxWidth: 900,
      margin: "0 auto",
      padding: "20px 20px 100px",
      display: "flex",
      flexDirection: "column",
      gap: 20,
    },

    // ---- Composants ----
    card: {
      background: colors.card,
      borderRadius: 16,
      padding: 20,
      boxShadow: colors.shadow,
      border: `1px solid ${colors.border}`,
      transition: "background-color 0.3s, box-shadow 0.2s",
    },
    input: {
      width: "100%",
      border: `1px solid ${colors.border}`,
      borderRadius: 12,
      padding: "12px 16px",
      fontSize: 15,
      backgroundColor: colors.inputBg,
      color: colors.text,
      outline: "none",
      boxSizing: "border-box",
      marginBottom: 12,
      fontFamily: theme.fontSans,
      transition: "border-color 0.2s, background-color 0.3s, color 0.3s",
    },
    select: {
      width: "100%",
      border: `1px solid ${colors.border}`,
      borderRadius: 12,
      padding: "12px 16px",
      fontSize: 15,
      backgroundColor: colors.inputBg,
      color: colors.text,
      outline: "none",
      appearance: "none",
      backgroundImage: `url("data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='${dark ? "%23cbd5e1" : "%2394a3b8"}' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3e%3cpolyline points='6 9 12 15 18 9'%3e%3c/polyline%3e%3c/svg%3e")`,
      backgroundRepeat: "no-repeat",
      backgroundPosition: "right 16px center",
      backgroundSize: 16,
      marginBottom: 12,
      boxSizing: "border-box",
      fontFamily: theme.fontSans,
      transition: "border-color 0.2s, background-color 0.3s, color 0.3s",
    },
    btn: (color = colors.accent) => ({
      background: color,
      color: "#fff",
      border: "none",
      borderRadius: 12,
      padding: "12px 24px",
      fontSize: 15,
      fontWeight: 700,
      cursor: "pointer",
      width: "100%",
      transition: "background 0.2s, transform 0.1s",
      fontFamily: theme.fontSans,
    }),
    btnSm: (color = colors.accent) => ({
      background: color,
      color: "#fff",
      border: "none",
      borderRadius: 8,
      padding: "6px 14px",
      fontSize: 13,
      fontWeight: 600,
      cursor: "pointer",
      fontFamily: theme.fontSans,
      transition: "background 0.2s",
    }),
    badge: (color) => ({
      background: color + "18",
      color: color,
      border: `1px solid ${color}40`,
      borderRadius: 20,
      padding: "4px 12px",
      fontSize: 12,
      fontWeight: 600,
      display: "inline-flex",
      alignItems: "center",
      gap: 4,
      fontFamily: theme.fontSans,
    }),
    label: {
      fontSize: 13,
      color: colors.textMuted,
      marginBottom: 6,
      display: "block",
      fontWeight: 600,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      fontFamily: theme.fontSans,
    },
    h2: {
      fontSize: 24,
      fontWeight: 800,
      marginBottom: 4,
      color: dark ? "#f1f5f9" : "#1e293b",
      fontFamily: theme.fontHeading,
    },
    h3: {
      fontSize: 16,
      fontWeight: 700,
      color: dark ? "#e2e8f0" : "#1e293b",
      marginBottom: 2,
      fontFamily: theme.fontHeading,
    },
    muted: {
      fontSize: 13,
      color: colors.textMuted,
      fontFamily: theme.fontSans,
    },
    row: {
      display: "flex",
      alignItems: "center",
      gap: 10,
    },
    between: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
    },

    // ---- Nouveaux styles utiles ----
    table: {
      width: "100%",
      borderCollapse: "collapse",
      fontSize: 14,
      fontFamily: theme.fontSans,
    },
    th: {
      background: dark ? "#1e293b" : "#f8fafc",
      padding: "12px 16px",
      textAlign: "left",
      fontWeight: 600,
      color: colors.textMuted,
      borderBottom: `2px solid ${colors.border}`,
      whiteSpace: "nowrap",
    },
    td: {
      padding: "12px 16px",
      borderBottom: `1px solid ${colors.border}`,
    },
    modalOverlay: {
      position: "fixed",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: "rgba(0,0,0,0.4)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 1000,
      animation: "fadeIn 0.2s",
    },
    modalContent: {
      background: colors.card,
      borderRadius: 16,
      padding: 24,
      maxWidth: 500,
      width: "90%",
      maxHeight: "90vh",
      overflowY: "auto",
      boxShadow: dark ? "0 20px 40px rgba(0,0,0,0.5)" : "0 20px 40px rgba(0,0,0,0.2)",
      transition: "background-color 0.3s",
    },
    spinner: (size = 20) => ({
      width: size,
      height: size,
      border: `3px solid ${dark ? "rgba(255,255,255,0.3)" : "rgba(0,0,0,0.2)"}`,
      borderTopColor: colors.accent,
      borderRadius: "50%",
      animation: "spin 0.6s linear infinite",
    }),

    // ---- Métadonnées ----
    cardBorder: colors.border,
    textMuted: colors.textMuted,
    textDim: colors.textDim,
    shadow: colors.shadow,
  };
};

// ✅ Export du hook useStyles (indispensable)
export function useStyles() {
  const { dark, toggle } = useTheme();
  const S = getStyles(dark);
  return { S, dark, toggle };
}