platform :ios, '15.0'
use_modular_headers!

target 'App' do
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  # Pas de CapacitorCordova
end