platform :ios, '14.0'

target 'App' do
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  # Ajoutez ici d'autres pods si nécessaire
end